### PR TITLE
Update vehicle_routing.py

### PR DESCRIPTION
**Pull request by ashwin-M-D**
The vehicle routing problem had issues with the comparison of touples and arrays which prevented it from working as expected. The Directions for movement were wrong as well. These issues have been fixed. The state output and any other environment variables have not been changed in any way whatsoever.

### CODE REVIEW

**Comment by mawbray** [comment]
Hi @hubbs5 @ashwin-M-D, I am playing around with the vehicle routing problem (on the master branch). Looking at the rewards, they are distributed as either 0 or -0.1 (generated from 100 episodes of a universally random policy). This indicates to me that there may still be a problem with the allocation/environment construction. Please could you look into this? If it is a problem I am happy to look into it further and try to remedy, if not please could you clarify why this distribution of rewards could be observed (I have run the test multiple times). Thanks for your help in advance :)

**Comment by ashwin-M-D** [comment]
Hello @mawbray 
The reward distribution is actually fine to train a reinforcement learning model. However, the values can be changed by passing the required values through env_config. The rewards distribution required for effective learning may change with different models and you can change them as required.

**Comment by mawbray** [comment]
Hi @ashwin-M-D, okay, thank you for the clarification. All the best :)

**Comment by osarwar** [comment]
@mawbray @ashwin-M-D Thanks for your help guys!

**Pull request merged**
